# Generated by Django 4.0.1 on 2022-01-23 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apitest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apitest_name', models.CharField(max_length=64, verbose_name='流程接口名称')),
                ('apitest_desc', models.CharField(max_length=128, null=True, verbose_name='流程接口描述')),
                ('apitester', models.CharField(max_length=16, verbose_name='测试负责人')),
                ('apitest_result', models.BooleanField(verbose_name='测试结果')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': '流程场景接口',
                'verbose_name_plural': '流程场景接口',
            },
        ),
        migrations.CreateModel(
            name='Apistep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100, verbose_name='接口名称')),
                ('api_url', models.CharField(max_length=200, verbose_name='接口url')),
                ('api_step', models.CharField(max_length=100, null=True, verbose_name='接口步骤')),
                ('api_param', models.CharField(max_length=800, verbose_name='接口参数和值')),
                ('api_method', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put')], default='get', max_length=200, null=True, verbose_name='请求方法')),
                ('api_except_result', models.CharField(max_length=200, verbose_name='预期结果')),
                ('api_response', models.CharField(max_length=5000, null=True, verbose_name='响应数据')),
                ('api_status', models.BooleanField(verbose_name='是否通过')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('Apitest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.apitest')),
            ],
        ),
    ]
